
#formato do arquivo
version: "3.9"

#especicar a rede
networks:
  algafood-network:
    driver: bridge
    
#especificar cada container q vai ser usado    
services:
  algafood-mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: ""
    ports:
      - "13307:3306"
    networks:
      - algafood-network
   
   #para armazenar estrutura de dados em memoria. para escalar mais de um container
  algafood-redis:
        image: redis:6.2.1-alpine
        networks:
        - algafood-network

  algafood-api:
    image: algafood-api
    command: ["/wait-for-it.sh", "algafood-mysql:3306", "-t", "30", "--", "java", "-jar", "api.jar"]
    environment:
      DB_HOST: algafood-mysql
      SPRING_SESSION_STORE_TYPE: redis
      SPRING_REDIS_HOST: algafood-redis
      SPRING_PROFILES_ACTIVE: development
    networks:
      - algafood-network
     #o container algafood-api so vai iniciar depois do mysql
    depends_on:
      - algafood-mysql
  
  #serve para sunir mais de um projeto
  algafood-proxy:
    build: ./nginx
    image: algafood-proxy
    ports:
      - "80:80"
    networks:
      - algafood-network
    depends_on:
      - algafood-api
 
 
 
 
 
 
 
 
 
 
 
 
 
  